--DROP TABLE flyway_schema_history;

DROP TABLE IF EXISTS price CASCADE;
DROP TABLE IF EXISTS ticker_relation CASCADE;
DROP TABLE IF EXISTS saved_stocks CASCADE;
DROP TABLE IF EXISTS ticker_company_info CASCADE;
DROP TABLE IF EXISTS ticker CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS ticker_type CASCADE;
DROP TABLE IF EXISTS market CASCADE;
DROP TABLE IF EXISTS locale CASCADE;
