spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

mars:
  inference:
    url: https://34-148-233-125.sslip.io
  api-key: ${MARS_API_KEY}

polygon:
  api-key: ${POLYGON_API_KEY}

finnhub:
  api-key: ${FINNHUB_API_KEY}

logging:
  level:
    org.hibernate.orm.jdbc.error: ERROR